"""Runs a small, hand-picked set of differently-styled questions through
both retrieval backends (BM25, the default, and the optional local
Chroma vector index) directly -- `.retrieve(query, top_k=5)`, no
`topic_filter` -- to isolate pure text-to-relevance matching from the
full agent pipeline's own topic-tag construction (which floods
`topic_filter` with every flagged marker's tags and would otherwise
dominate BM25's tag-boost regardless of the query text itself).

Manual, deliberate, real cost (a handful of live Bedrock Titan
Embeddings calls for the Chroma queries) -- not part of pytest or CI,
same tier as `scripts/build_vector_index.py`.

Run with:
    AWS_PROFILE=dev python scripts/compare_retrievers.py

Regenerates docs/RETRIEVAL_COMPARISON.md, the same "regenerate a
checked-in doc from a live run" pattern `scripts/update_eval_history.py`
and `scripts/run_examples.py` already use.

**Important caveat this comparison alone doesn't show**: a retrieval
difference here does not automatically mean a different final answer.
Checked directly (see docs/DECISIONS.md's Stage A entry for the full
experiment): with the default MockNarrator, `HealthAgent.ask()`'s
returned answer text is byte-for-byte identical between backends except
for the trailing "Sources:" line -- `mock_narrator.py` only ever reads
`retrieved_chunks` to build that citation footer (`_sources_line()`);
every other line comes from `grounded_facts`/`questionnaire_modifiers`,
never from a chunk's own `content`. With the real Bedrock narrator, the
retrieved chunks' *names* do reach the model's prompt (via the
already-grounded text `BedrockNarrator` asks it to rephrase), but two
repeated runs per backend showed content differences at least as large
between two runs of the *same* backend as between backends -- Bedrock's
own generation isn't run at a fixed temperature/seed, so a couple of
runs isn't enough evidence to attribute a "better" answer to retrieval
choice specifically. Either way, the retrieved chunk's own text content
is never actually inserted into a prompt or template anywhere in this
codebase today -- retrieval currently drives *citations*, not
*generation content*. See docs/DECISIONS.md for the full reasoning on
whether/how to close that gap.
"""

from __future__ import annotations

from pathlib import Path

from care_agent.retrieval.bm25_retriever import KnowledgeRetriever
from care_agent.retrieval.chroma_retriever import ChromaRetriever

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "docs" / "RETRIEVAL_COMPARISON.md"

# Deliberately varied styles: exact biomarker/technical phrasing (where
# BM25's term overlap should do well), natural-language paraphrases
# (where Chroma's semantic match should do well), and a couple of
# ambiguous/short ones in between -- the point is covering the spectrum,
# not cherry-picking examples that make one backend look best.
QUERIES = [
    "What foods should I eat to lower my LDL cholesterol?",
    "LDL-C 162 mg/dL high",
    "fish oil dose for triglycerides",
    "I have knee pain, how should I exercise?",
    "trend in my cholesterol over time",
    "am I at risk for diabetes because of my family history",
    "vitamin D low what does that mean",
    "high hs-CRP inflammation marker",
]

TOP_K = 5


def _render_results(results) -> str:
    if not results:
        return "  (no results)"
    return "\n".join(f"  {r.score:>8.4f}  {r.chunk.id:<20} {r.chunk.title}" for r in results)


def main() -> None:
    bm25 = KnowledgeRetriever()
    chroma = ChromaRetriever()

    lines = [
        "# Retrieval backend comparison: BM25 vs. local Chroma",
        "",
        "Generated by `scripts/compare_retrievers.py` -- both backends queried "
        "directly (`.retrieve(query, top_k=5)`, no `topic_filter`) against the "
        "real, committed 68-chunk `data/knowledge_base.jsonl` / `data/vector_index/`. "
        "Scores are not comparable across backends (BM25's is an unbounded "
        "TF-IDF-style score; Chroma's is a cosine similarity in [-1, 1]) -- "
        "compare which chunks were surfaced, not the score magnitudes.",
        "",
        f"`overlap` = how many of the top {TOP_K} chunk ids the two backends agree on.",
        "",
        "**Does this reach the final answer?** With the default MockNarrator, no -- "
        "`HealthAgent.ask()`'s returned text is identical between backends except for "
        "the trailing `Sources:` line (`mock_narrator.py` only reads `retrieved_chunks` "
        "to build that citation footer; every other line comes from `grounded_facts`/"
        "`questionnaire_modifiers`, never from a chunk's own `content`). With the real "
        "Bedrock narrator, retrieved chunks' *names* reach the model's prompt, but "
        "repeated runs showed run-to-run variance (Bedrock isn't called at a fixed "
        "temperature/seed) at least as large as the variance between backends -- not "
        'enough evidence to attribute a "better" answer to retrieval choice alone. '
        "Retrieval currently drives citations, not generation content, anywhere in this "
        "codebase -- see docs/DECISIONS.md for the full experiment and reasoning.",
        "",
    ]

    total_overlap = 0
    for query in QUERIES:
        bm25_results = bm25.retrieve(query, top_k=TOP_K)
        chroma_results = chroma.retrieve(query, top_k=TOP_K)
        bm25_ids = {r.chunk.id for r in bm25_results}
        chroma_ids = {r.chunk.id for r in chroma_results}
        overlap = len(bm25_ids & chroma_ids)
        total_overlap += overlap

        lines.append(f"## `{query}`")
        lines.append("")
        lines.append(f"overlap: {overlap}/{TOP_K}")
        lines.append("")
        lines.append("**BM25:**")
        lines.append("```")
        lines.append(_render_results(bm25_results))
        lines.append("```")
        lines.append("")
        lines.append("**Chroma:**")
        lines.append("```")
        lines.append(_render_results(chroma_results))
        lines.append("```")
        lines.append("")

    lines.insert(6, f"Average overlap across {len(QUERIES)} queries: {total_overlap / len(QUERIES):.1f}/{TOP_K}.")
    lines.insert(7, "")

    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
