"""Regenerates examples/example_output.md from the live agent.

Run with: python scripts/run_examples.py
"""
from __future__ import annotations

from pathlib import Path

from care_agent.agent import HealthAgent
from care_agent.data_store import DataStore

REPO_ROOT = Path(__file__).resolve().parent.parent
OUT_PATH = REPO_ROOT / "examples" / "example_output.md"


def render_trace_summary(trace) -> str:
    lines = [f"- intent: `{trace.intent}`", f"- narrator backend: `{trace.narrator_backend}`"]
    lines.append(f"- tool calls: {len(trace.tool_calls)}")
    for tc in trace.tool_calls:
        lines.append(f"  - `{tc.name}({tc.args})` -> {tc.result_summary}")
    lines.append(f"- retrieved knowledge chunks: {len(trace.retrieved_chunks)}")
    for rc in trace.retrieved_chunks:
        lines.append(f"  - `{rc.chunk.id}` ({rc.chunk.source_name}, score={rc.score})")
    lines.append(f"- grounded facts: {len(trace.grounded_facts)}")
    for gf in trace.grounded_facts:
        lines.append(f"  - [{gf.source_type}] {gf.claim} (ref: `{gf.source_ref}`)")
    if trace.limitations:
        lines.append(f"- limitations surfaced: {len(trace.limitations)}")
        for lim in trace.limitations:
            lines.append(f"  - [{lim.kind}] {lim.detail}")
    lines.append("- safety checks:")
    for sc in trace.safety_checks:
        status = "PASS" if sc.passed else "FAIL"
        lines.append(f"  - {sc.name}: {status}" + (f" ({sc.detail})" if sc.detail else ""))
    return "\n".join(lines)


def main() -> None:
    agent = HealthAgent()
    questions = DataStore().get_sample_questions()

    parts = [
        "# Example Output — Sample Scenarios\n",
        "Generated by `scripts/run_examples.py` against the shipped sample dataset "
        "(`user_demo_001`), using the default mock narrator (no LLM / no external API).\n",
    ]

    for q in questions:
        response = agent.ask(user_id=q["user_id"], question_text=q["text"], question_id=q["id"])
        parts.append(f"## {q['id']}\n")
        parts.append(f"**Question:** {q['text']}\n")
        parts.append(f"**Expected capabilities:** {', '.join(q['expected_capabilities'])}\n")
        parts.append("**Answer:**\n")
        parts.append("```\n" + response.answer + "\n```\n")
        parts.append(f"**Safe:** {response.safe}\n")
        parts.append("<details>\n<summary>Execution trace</summary>\n")
        parts.append(render_trace_summary(response.trace) + "\n")
        parts.append("</details>\n")

    OUT_PATH.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {OUT_PATH}")


if __name__ == "__main__":
    main()
